### ISSUE TITLE
reviewdog support

### ISSUE THREAD

**Issue by santiagodoldan** [Bearer/bearer-action#17]
Are there any plans to implement a GitHub action using https://github.com/reviewdog? Similar to https://github.com/reviewdog/action-brakeman

**Comment by gotbadger** [comment]
To cut a long story short it is something we would love to support but its not planned just yet as we are still concentrating efforts on improving the CLI.

On the implmentation side it would be great to have native support in the CLI itself as a report format but it should also be possible to write a translation from the current summary json to the reviewdog error format and we would accept PR's that added that support.

If you want to subscribe to this issue I'll post again if anything changes.

**Comment by gotbadger** [comment]
We are currently working on https://github.com/Bearer/bearer/pull/984 which adds SARIF support this should make adding reviewdog support much easier once we have this change in im going to look at whats required.

**Comment by gotbadger** [comment]
We will be working on this shortly https://github.com/Bearer/bearer/issues/1026

**Comment by gotbadger** [comment]
@santiagodoldan you can now do this with the following action

```yml
name: Bearer PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        with:
          format: rdjson
          output: rd.json
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
        run: |
          cat rd.json | reviewdog -f=rdjson -reporter=github-pr-review
 ```
 
you need to use a personal access token with `github-pr-review` but it works the best. 

Example here: https://github.com/gotbadger/bear-publishing/pull/1#pullrequestreview-1470012926

Going to close this issue now as complete feel free to reopen if you have any more questions.
