### ISSUE TITLE
Bearer step output is empty

### ISSUE THREAD

**Issue by santiagodoldan** [Bearer/bearer-action#22]
We are having issues today where the output of the berarer step is empty, we tried what the documentation suggests 👇 and also using the GitHub Actions steps API as shown below as well.

```
      - name: Display Bearer Summary
        uses: actions/github-script@v6
        with:
          script: |
            // github does not support multiline outputs so report is encoded
            const report = decodeURIComponent(`$`);
            const passed = `$` == "0";
            if(!passed){ core.setFailed(report); } <<<<<---- This returns the char `$`, nothing else
```

```
      - name: Bearer
        id: bearer
        uses: bearer/bearer-action@v1.0
        with:
          config-file: ./bearer.yml
      - name: Get result
        run: echo "${{steps.brakeman.outputs.result}}" <<<<<---- Empty
```

Not sure if the changes that were merged today are causing this issue, it would be great to be able to use different versions of bearer-action and not always using 1.0 that points to latest changes from main branch.
