### ISSUE TITLE
Support security and privacy report types

### ISSUE THREAD

**Issue by santiagodoldan** [Bearer/bearer-action#35]
Hey 👋 We would like to use the bearer action to run both, security and privacy reports, would be ok introducing a new config here -> https://github.com/Bearer/bearer-action/blob/main/action.yml#L76-L86? I'd love to help if that's something you are open to include in the action. Thank you so much 🙌

**Comment by elsapet** [comment]
Hey @santiagodoldan - thanks for your great suggestion! I'll discuss it with the team, as there may be some considerations about consistency (a lot of the action's other options are security-specific, for example). 

That said, it is currently possible for the Bearer action to run a privacy report by using a (Bearer configuration file)[https://docs.bearer.com/reference/config/] to set the report format to `privacy`, for example: 

```
report:
    report: privacy
```

And then running the action using the `config-file` option to point to this file

```
steps:
  - uses: actions/checkout@v3
  - name: Bearer
    uses: bearer/bearer-action@v2
    with:
      config-file: '/some/path/bearer.yml'
```

Would using a config file be an option for you?
